import macbookAir13 from '../../assets/laptops/Apple_MacBook_Air_13.png'
import macbookPro13 from '../../assets/laptops/Apple_MacBook_Pro_13.png'
import macbookPro14 from '../../assets/laptops/Apple_MacBook_Pro_14.png'
import macbookPro16 from '../../assets/laptops/Apple_MacBook_Pro_16.png'
import vivobookPro16 from '../../assets/laptops/Asus_VivoBook_Pro_16.png'
import zenbook14 from '../../assets/laptops/Asus_ZenBook_14.png'
import alienwareM15R7 from '../../assets/laptops/Dell_Alienware_M15_R7.png'
import inspiron16 from '../../assets/laptops/Dell_Inspiron_16.png'
import latitude9330 from '../../assets/laptops/Dell_Latitude_9330.png'
import precision3571 from '../../assets/laptops/Dell_Precision_3571.png'
import vostro7620 from '../../assets/laptops/Dell_Vostro_7620.png'
import xps13Plus from '../../assets/laptops/Dell_XPS_13_Plus.png'
import crosshair17 from '../../assets/laptops/MSI_Crosshair_17.png'
import katanaGf66 from '../../assets/laptops/MSI_Katana_GF66.png'
import katanaGf76 from '../../assets/laptops/MSI_Katana_GF76.png'
import pulseGl76 from '../../assets/laptops/MSI_Pulse_GL76.png'
import stealth15M from '../../assets/laptops/MSI_Stealth_15M.png'
import summitE16 from '../../assets/laptops/MSI_Summit_E16.png'
import thinGf63 from '../../assets/laptops/MSI_Thin-GF63.png'
import vectorGp76 from '../../assets/laptops/MSI_Vector_GP76.png'
import rog17 from '../../assets/laptops/ROG_17.png'
import rogG15 from '../../assets/laptops/ROG_G15.png'
import tufGamingA15 from '../../assets/laptops/TUF_Gaming_A15.png'
import tufGamingF15 from '../../assets/laptops/TUF_Gaming_F15.png'



export const NotebooksItems = [
  {
    id: 25,
    name: "Apple MacBook Air 13 M2 Chip 8GB/256GB LL/A",
    brand: "Apple",
    screenSize: "13.6 inch",
    resolution: "2560x1664",
    touchScreen: false,
    cpuType: "Apple",
    cpu: "Apple M2 Chip",
    core: "Octa-Core 3.5 MHz Max",
    ram: "8GB",
    ssd: "256GB",
    hdd: false,
    gpuModel: "Apple 8-core GPU",
    gpuType: "Integrated",
    display: "IPS",
    os: "macOS",
    bluetooth: "Bluetooth 5.0",
    battery: "Li-Ion 52.6 Wh Up to 18 hours",
    weight: "1.24 kg",
    image: macbookAir13,
    price: 1200
  },
  {
    id: 26,
    name: "Apple MacBook Pro 13 M2 Chip 2022 8GB/512GB LL/A",
    brand: "Apple",
    screenSize: "13.3 inch",
    resolution: "2560x1600",
    touchScreen: false,
    cpu: "Apple M2 Chip",
    cpuType: "Apple",
    ram: "8GB",
    ssd: "512GB",
    hdd: false,
    gpuType: "Integrated",
    display: "IPS",
    os: "macOS",
    bluetooth: "Bluetooth 5.0",
    weight: "1.20 kg",
    image: macbookPro13,
    price: 1600
  },
  {
    id: 27,
    name: "Apple Z15G004EQ MacBook Pro 14 inch 2021 32/2TB",
    brand: "Apple",
    screenSize: "14.2 inch",
    touchScreen: false,
    cpu: "Apple M1 Pro",
    cpuType: "Apple",
    core: "8-core CPU",
    ram: "32GB",
    ssd: "2TB",
    hdd: false,
    gpuModel: "Apple 14-core GPU",
    gpuType: "Integrated",
    display: "IPS",
    os: "macOS",
    image: macbookPro14,
    price: 3800
  },
  {
    id: 28,
    name: "Apple Z14V00234 MacBook Pro 16 inch 2021 32/1TB",
    brand: "Apple",
    screenSize: "13.6 inch",
    resolution: "2560x1664",
    touchScreen: false,
    cpu: "Apple M2 Chip",
    cpuType: "Apple",
    core: "Octa-Core 3.5 MHz Max",
    ram: "8GB",
    ssd: "8888",
    hdd: false,
    gpuModel: "Apple 8-core GPU",
    gpuType: "Integrated",
    display: "IPS",
    os: "macOS",
    bluetooth: "Bluetooth 5.0",
    battery: "Li-Ion 52.6 Wh Up to 18 hours",
    weight: "1.24 kg",
    image: macbookPro16,
    price: 4200
  },
  {
    id: 29,
    name: "Asus VivoBook Pro 16 OLED M7601RM-MX070W",
    brand: "Asus",
    screenSize: "16 inch",
    resolution: "3200X2000",
    cpu: "AMD Ryzen 9 6900HX",
    cpuType: "AMD",
    core: "Octa-Core 3.3 GHz - 4.9 Max",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3060",
    gpuType: "Dedicated",
    os: "Windows 11 Home",
    weight: "2.3 kg",
    image: vivobookPro16,
    price: 2300
  },
  {
    id: 30,
    name: "Asus ZenBook 14 UM3402YA-KP290",
    brand: "Asus",
    screenSize: "14 inch",
    resolution: "2560x1600",
    cpu: "AMD Ryzen 5 5625U",
    cpuType: "AMD",
    core: "Hexa-Core 2.3 GHz - 4.3 Max",
    ram: "16GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "AMD Radeon Graphics",
    gpuType: "Integrated",
    os: "Free Dos",
    image: zenbook14,
    price: 1050
  },
  {
    id: 31,
    name: "Dell Alienware M15 R7",
    brand: "Dell",
    screenSize: "15.6 inch",
    resolution: "2560x1440",
    touchScreen: false,
    cpu: "Intel Core i7 12700H",
    cpuType: "Intel",
    core: "14-Core - 3.5-4.7 GHz",
    ram: "32GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3060 6GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Windows 11 Home",
    bluetooth: "Bluetooth 5.0",
    image: alienwareM15R7,
    price: 3400
  },
  {
    id: 32,
    name: "Dell Inspiron 16 5620",
    brand: "Dell",
    screenSize: "16 inch",
    resolution: "FHD+",
    touchScreen: false,
    cpu: "Intel Core i5 1235U",
    cpuType: "Intel",
    core: "10-Core - 3.3-4.4 GHz",
    ram: "8GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "Intel UHD Graphics",
    gpuType: "Integrated",
    display: "IPS",
    os: "Windows 11 Home",
    image: inspiron16,
    price: 1100
  },
  {
    id: 33,
    name: "Dell Latitude 9330",
    brand: "Dell",
    screenSize: "13.3 inch",
    resolution: "2560x1600",
    touchScreen: true,
    cpu: "Intel Core i7 1260U",
    cpuType: "Intel",
    core: "10-Core - 3.5-4.7 GHz",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "intel iris Xe Graphics",
    gpuType: "Integrated",
    os: "Windows 11 Pro",
    bluetooth: "Bluetooth 5.0",
    image: latitude9330,
    price: 3200
  },
  {
    id: 34,
    name: "Dell Precision 3571",
    brand: "Dell",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i9 12900H",
    cpuType: "Intel",
    core: "14-Core - 3.8-5.0 GHz",
    ram: "16GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "Nvidia RTX A2000 8GB",
    gpuType: "Dedicated",
    os: "Ubuntu",
    bluetooth: "Bluetooth 5.2",
    battery: "Li-Ion 6-cell",
    image: precision3571,
    price: 2900
  },
  {
    id: 35,
    name: "Dell Vostro 7620",
    brand: "Dell",
    screenSize: "16 inch",
    resolution: "3072x1920",
    touchScreen: false,
    cpu: "Intel Core i7 12700H",
    cpuType: "Intel",
    core: "14-Core - 3.5-4.7 GHz",
    ram: "16GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3050 4GB",
    gpuType: "Dedicated",
    os: "Windows 11 Pro",
    bluetooth: "Bluetooth 5.2",
    battery: "3-cell 56 Wh",
    weight: "2 kg",
    image: vostro7620,
    price: 2000
  },
  {
    id: 36,
    name: "Dell XPS 13 Plus",
    brand: "Dell",
    screenSize: "13.4 inch",
    resolution: "3456x2160",
    touchScreen: true,
    cpu: "Intel Core i7 1260P",
    cpuType: "Intel",
    core: "12-Core - 3.4-4.7 GHz",
    ram: "32GB",
    ssd: "2TB",
    hdd: false,
    gpuModel: "intel iris Xe Graphics",
    gpuType: "Integrated",
    os: "Windows 11 Pro",
    bluetooth: "Bluetooth 5.2",
    battery: "Li-Ion 3-cell",
    weight: "1.26 kg",
    image: xps13Plus,
    price: 3450
  },
  {
    id: 37,
    name: "MSI Crosshair 17 Black",
    brand: "MSI",
    screenSize: "17.3 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i7 12700H",
    cpuType: "Intel",
    core: "14-Core - 3.5-4.7 GHz",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3060 6GB",
    gpuType: "Dedicated",
    os: "Free Dos",
    image: crosshair17,
    price: 2250
  },
  {
    id: 38,
    name: "MSI Katana GF66 Black",
    brand: "MSI",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i5 12500H",
    cpuType: "Intel",
    core: "12-Core - 3.3-4.5 GHz",
    ram: "8GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3050 4GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.2",
    battery: "3-cell, 53.5 WHr",
    weight: "2.25 kg",
    image: katanaGf66,
    price: 1400
  },
  {
    id: 39,
    name: "MSI Katana GF76 Black",
    brand: "MSI",
    screenSize: "17.3 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i7 12700H",
    cpuType: "Intel",
    core: "14-Core - 3.5-4.7 GHz",
    ram: "16GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3060 6GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.2",
    weight: "2.6 kg",
    image: katanaGf76,
    price: 1950
  }, 
  {
    id: 40,
    name: "MSI Pulse GL76 Black",
    brand: "MSI",
    screenSize: "17.3 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i9 12900H",
    cpuType: "Intel",
    core: "14-Core - 3.8-5.0 GHz",
    ram: "32GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX 3070 Ti 8GB",
    gpuType: "Dedicated",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.2",
    battery: "Li-Ion 52.6 Wh Up to 18 hours",
    weight: "2.2 kg",
    image: pulseGl76,
    price: 2830
  },
  {
    id: 41,
    name: "MSI Stealth 15M ",
    brand: "MSI",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i7 1280P",
    cpuType: "Intel",
    core: "14-Core - 3.6-4.8 GHz",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3060 Max-Q 6GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.2",
    battery: "Li-Ion 52.6 Wh Up to 18 hours",
    weight: "1.7 kg",
    image: stealth15M,
    price: 2000
  },
  {
    id: 42,
    name: "MSI Summit E16 Flip",
    brand: "MSI",
    screenSize: "16 inch",
    resolution: "2560x1664",
    touchScreen: true,
    cpu: "Intel Core i7 1280P",
    cpuType: "Intel",
    core: "14-Core - 3.6-4.8 GHz",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "intel iris Xe Graphics",
    gpuType: "Integrated",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.1",
    battery: "Li-Ion 3-cell",
    weight: "1.7 kg",
    image: summitE16,
    price: 2350
  },
  {
    id: 43,
    name: "MSI GF63 Thin",
    brand: "MSI",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i5 11400H + HM570",
    cpuType: "Intel",
    core: "Hexa-Core 4.5 GHz",
    ram: "8GB",
    ssd: "256GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3050 Max-Q 4GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.1",
    weight: "2.1 kg",
    image: thinGf63,
    price: 1050
  },
  {
    id: 44,
    name: "MSI Vector GP76",
    brand: "MSI",
    screenSize: "17.3 inch",
    resolution: "2560x1440",
    touchScreen: false,
    cpu: "Intel Core i9 12900HX",
    cpuType: "Intel",
    core: "16-Core - 3.6-5.0 GHz",
    ram: "64GB",
    ssd: "2TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3080 Ti 16GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Windows 11 Pro",
    bluetooth: "Bluetooth 5.2",
    image: vectorGp76,
    price: 5800
  },
  {
    id: 45,
    name: "Asus ROG Strix 17 Black",
    brand: "Asus",
    screenSize: "17.3 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "AMD Ryzen 7 6800H",
    cpuType: "AMD",
    core: "Octa-Core 3.2 GHz - 4.7 Max",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3050 4GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.2",
    weight: "2.3 kg",
    image: rog17,
    price: 1750
  },
  {
    id: 46,
    name: "Asus ROG Strix G15",
    brand: "Asus",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "AMD Ryzen 7 4800H",
    cpuType: "AMD",
    core: "Octa-Core 2.9 GHz - 4.2 Max",
    ram: "16GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3050 TI 4GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Windows 11 Home",
    image: rogG15,
    price: 900
  },
  {
    id: 47,
    name: "Asus TUF A15",
    brand: "Asus",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "AMD Ryzen 7 5800H",
    cpuType: "AMD",
    core: "Octa-Core 3.2 GHz - 4.4 Max",
    ram: "16GB",
    ssd: "1TB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3060 6GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    image: tufGamingA15,
    price: 800
  },
  {
    id: 48,
    name: "Asus TUF F15",
    brand: "Asus",
    screenSize: "15.6 inch",
    resolution: "1920x1080",
    touchScreen: false,
    cpu: "Intel Core i5 11400H",
    cpuType: "Intel",
    core: "Hexa-Core 4.5 GHz",
    ram: "16GB",
    ssd: "512GB",
    hdd: false,
    gpuModel: "NVIDIA GeForce RTX3050 4GB",
    gpuType: "Dedicated",
    display: "IPS",
    os: "Free Dos",
    bluetooth: "Bluetooth 5.2",
    battery: "Li-Ion 4-cell",
    weight: "2.2 kg",
    image: tufGamingF15,
    price: 1000
  }

]